# Generated by Django 3.1.7 on 2021-03-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasaPsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godinaRodjenja', models.CharField(max_length=15)),
                ('pol', models.CharField(max_length=10)),
                ('informacije', models.TextField(max_length=1000)),
                ('rasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_app.rasapsa')),
            ],
        ),
    ]
