# Generated by Django 3.1.7 on 2021-03-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthYear', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Pas',
        ),
        migrations.DeleteModel(
            name='RasaPsa',
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_app.dogbreed'),
        ),
    ]
