# Generated by Django 3.1.7 on 2021-03-11 20:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0002_auto_20210311_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
    ]
