# Generated by Django 3.1.7 on 2021-03-12 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0005_auto_20210312_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
