# Generated by Django 3.1.7 on 2021-03-13 22:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0006_dog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='pictures'),
        ),
    ]
