# Generated by Django 3.1.7 on 2021-03-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0008_dog_image6'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-date']},
        ),
    ]
