# Generated by Django 3.1.7 on 2021-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0012_auto_20210315_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
